version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget.exe restore LcmsSpectator.sln
configuration: Release
platform: Any CPU
build:
  project: LcmsSpectator.sln
  verbosity: minimal
test:
  categories:
    except:
    - PNL_Domain
artifacts:
- path: LcmsSpectator/bin/Release
  name: LCMS-Spectator
